name: Deploy to Production

on:
    repository_dispatch:
        types: [deploy_app]

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            -
                name: Check out the repo
                uses: actions/checkout@v4

            - 
                name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKER_USERNAME }}
                    password: ${{ secrets.DOCKER_PASSWORD }}
            
            -
                run: docker compose up -d --build --force-recreate --no-deps